apiVersion: platformref.crossplane.io/v1alpha1
kind: XCluster
metadata:
  name: eks-dev-1
spec:
  id: eks-dev-1
  parameters:
    nodes:
      count: 1
      size: small
    services:
      operators:
        prometheus:
          version: "15.0.1"
  cloud: aws
  writeConnectionSecretToRef:
    name: platform-ref-aws-kubeconfig
    namespace: upbound-system