---
apiVersion: aws.platformref.crossplane.io/v1alpha1
kind: XNetwork
metadata:
  name: my-vpc
spec:
  compositionRef:
    name: aws.xnetworks.platformref.crossplane.io
  compositionSelector:
    matchLabels:
      cloud: aws
      network: vpc